export type BootstrapMapCategory =
  | 'RESTAURANT'
  | 'HOTEL'
  | 'TOUR'
  | 'BEACH'
  | 'POINT'
  | 'CONVENIENCE';

export interface MapBootstrapLocation {
  id: string;
  mapSearchType: BootstrapMapCategory;
  name: string;
  description: string;
  category: string;
  location: string;
  photoUrl?: string;
  latitude: number;
  longitude: number;
  rating?: number | null;
  averagePrice?: number | null;
}

// Launch snapshot generated from the backend's real Noronha seed catalog.
export const NORONHA_MAP_BOOTSTRAP: ReadonlyArray<MapBootstrapLocation> = [
  {"id":"CURATED-POINT-1","mapSearchType":"BEACH","name":"Baía do Sancho","description":"Praia símbolo de Noronha, com falésias, mirantes e mar transparente para banho e snorkel.","category":"Praia","location":"Parque Nacional Marinho","photoUrl":"/assets/places/baia-do-sancho.jpg","latitude":-3.8547,"longitude":-32.4406},
  {"id":"CURATED-POINT-2","mapSearchType":"BEACH","name":"Baía dos Porcos","description":"Enseada pequena, rochosa e muito fotogênica, com vista direta para o Morro Dois Irmãos.","category":"Praia","location":"Entre Sancho e Cacimba do Padre","latitude":-3.8533,"longitude":-32.4358},
  {"id":"CURATED-POINT-3","mapSearchType":"BEACH","name":"Cacimba do Padre","description":"Praia ampla, conhecida pelo surf e pelo visual do Morro Dois Irmãos.","category":"Praia","location":"Costa oeste","latitude":-3.8508,"longitude":-32.4317},
  {"id":"CURATED-POINT-4","mapSearchType":"BEACH","name":"Praia do Bode","description":"Praia de acesso simples e clima mais tranquilo, boa para caminhar e ver o pôr do sol.","category":"Praia","location":"Costa oeste","latitude":-3.8493,"longitude":-32.4266},
  {"id":"CURATED-POINT-5","mapSearchType":"BEACH","name":"Praia do Americano","description":"Faixa de areia reservada entre Boldró e Bode, boa para quem procura menos movimento.","category":"Praia","location":"Costa oeste","latitude":-3.8484,"longitude":-32.4241},
  {"id":"CURATED-POINT-6","mapSearchType":"BEACH","name":"Praia do Boldró","description":"Praia de ondas e piscinas na maré baixa, próxima a um dos mirantes mais procurados da ilha.","category":"Praia","location":"Boldró","latitude":-3.8474,"longitude":-32.4217},
  {"id":"CURATED-POINT-7","mapSearchType":"BEACH","name":"Praia da Conceição","description":"Praia acessível, com vista para o Morro do Pico e um dos melhores fins de tarde da ilha.","category":"Praia","location":"Vila dos Remédios","latitude":-3.8422,"longitude":-32.4173},
  {"id":"CURATED-POINT-8","mapSearchType":"BEACH","name":"Praia do Meio","description":"Praia central entre Conceição e Cachorro, boa para banho quando o mar está calmo.","category":"Praia","location":"Centro histórico","latitude":-3.8409,"longitude":-32.4153},
  {"id":"CURATED-POINT-9","mapSearchType":"BEACH","name":"Praia do Cachorro","description":"Praia urbana, perto da Vila dos Remédios, com acesso fácil e movimento no fim do dia.","category":"Praia","location":"Vila dos Remédios","latitude":-3.84,"longitude":-32.4138},
  {"id":"CURATED-POINT-10","mapSearchType":"BEACH","name":"Praia da Biboca","description":"Trecho rochoso aos pés da Fortaleza dos Remédios, bom para fotos e leitura histórica da costa.","category":"Praia","location":"Centro histórico","latitude":-3.8392,"longitude":-32.4122},
  {"id":"CURATED-POINT-11","mapSearchType":"BEACH","name":"Praia do Porto de Santo Antônio","description":"Área de chegada dos barcos, com naufrágio próximo e águas geralmente boas para snorkel.","category":"Praia","location":"Porto","latitude":-3.8334,"longitude":-32.4046},
  {"id":"CURATED-POINT-12","mapSearchType":"BEACH","name":"Praia da Caieira","description":"Praia de natureza mais selvagem, próxima ao Buraco da Raquel e ao Museu do Tubarão.","category":"Praia","location":"Região do Porto","latitude":-3.8321,"longitude":-32.3991},
  {"id":"CURATED-POINT-13","mapSearchType":"BEACH","name":"Praia do Atalaia","description":"Piscina natural sensível, com visita controlada e agendamento pelo Parque Nacional.","category":"Praia","location":"Atalaia","latitude":-3.8438,"longitude":-32.3958},
  {"id":"CURATED-POINT-14","mapSearchType":"BEACH","name":"Praia do Sueste","description":"Baía protegida, procurada para snorkel e observação de tartarugas e vida marinha.","category":"Praia","location":"Litoral sudeste","latitude":-3.865,"longitude":-32.4225},
  {"id":"CURATED-POINT-15","mapSearchType":"BEACH","name":"Praia do Leão","description":"Praia extensa e preservada, com forte presença de tartarugas e visual selvagem.","category":"Praia","location":"Litoral sul","latitude":-3.8732,"longitude":-32.4248},
  {"id":"CURATED-POINT-16","mapSearchType":"BEACH","name":"Enseada dos Abreus","description":"Piscinas naturais acessadas por trilha agendada, indicada para maré baixa e guia credenciado.","category":"Praia","location":"Sueste","latitude":-3.8667,"longitude":-32.4146},
  {"id":"CURATED-POINT-17","mapSearchType":"POINT","name":"Mirante dos Dois Irmãos","description":"Mirante clássico para fotografar a Baía dos Porcos e os morros mais famosos de Noronha.","category":"Mirante","location":"PIC Sancho","latitude":-3.852,"longitude":-32.4368},
  {"id":"CURATED-POINT-18","mapSearchType":"POINT","name":"Mirante do Boldró","description":"Ponto tradicional para pôr do sol com vista da costa oeste e do Morro Dois Irmãos.","category":"Mirante","location":"Boldró","latitude":-3.8478,"longitude":-32.4229},
  {"id":"CURATED-POINT-19","mapSearchType":"POINT","name":"Mirante da Baía dos Golfinhos","description":"Ponto de observação dos golfinhos rotadores, especialmente nas primeiras horas do dia.","category":"Mirante","location":"Parque Nacional Marinho","latitude":-3.8524,"longitude":-32.4446},
  {"id":"CURATED-POINT-20","mapSearchType":"POINT","name":"Ponta das Caracas","description":"Mirante com vista para formações vulcânicas, ilhas secundárias e mar aberto.","category":"Mirante","location":"Sueste","latitude":-3.8721,"longitude":-32.4192},
  {"id":"CURATED-POINT-21","mapSearchType":"POINT","name":"Buraco da Raquel","description":"Formação rochosa histórica e ponto contemplativo próximo ao Porto.","category":"Mirante","location":"Região do Porto","latitude":-3.8311,"longitude":-32.3978},
  {"id":"CURATED-POINT-22","mapSearchType":"POINT","name":"Ponta da Sapata","description":"Extremo de paisagem dramática, visto em passeios de barco e trilhas autorizadas.","category":"Mirante","location":"Extremo oeste","latitude":-3.8577,"longitude":-32.4552},
  {"id":"CURATED-POINT-23","mapSearchType":"POINT","name":"Fortaleza Nossa Senhora dos Remédios","description":"Fortificação histórica com vista para o mar e para o centro da ilha.","category":"Histórico","location":"Vila dos Remédios","latitude":-3.8394,"longitude":-32.4124},
  {"id":"CURATED-POINT-24","mapSearchType":"POINT","name":"Igreja Nossa Senhora dos Remédios","description":"Igreja histórica no coração da Vila dos Remédios, próxima ao casario e às praças.","category":"Histórico","location":"Vila dos Remédios","latitude":-3.8409,"longitude":-32.4108},
  {"id":"CURATED-POINT-25","mapSearchType":"POINT","name":"Palácio São Miguel","description":"Sede administrativa histórica da ilha, em área central e fácil de combinar com a Vila.","category":"Histórico","location":"Vila dos Remédios","latitude":-3.8411,"longitude":-32.4102},
  {"id":"CURATED-POINT-26","mapSearchType":"POINT","name":"Memorial Noronhense","description":"Espaço cultural para entender a formação histórica e social de Fernando de Noronha.","category":"Cultura","location":"Vila dos Remédios","latitude":-3.8408,"longitude":-32.411},
  {"id":"CURATED-POINT-27","mapSearchType":"POINT","name":"Museu do Tubarão","description":"Ponto de visita sobre vida marinha, com restaurante próximo e vista da região do Porto.","category":"Cultura","location":"Porto","latitude":-3.8324,"longitude":-32.3992},
  {"id":"CURATED-POINT-28","mapSearchType":"POINT","name":"Capela de São Pedro dos Pescadores","description":"Capela pequena e simbólica, ligada à tradição dos pescadores e à paisagem do Porto.","category":"Cultura","location":"Porto","latitude":-3.8332,"longitude":-32.4012},
  {"id":"CURATED-POINT-29","mapSearchType":"POINT","name":"Centro de Visitantes ICMBio","description":"Base para informações, ingressos e agendamentos de atrativos do Parque Nacional.","category":"Serviço turístico","location":"Boldró","latitude":-3.849,"longitude":-32.419},
  {"id":"CURATED-POINT-30","mapSearchType":"POINT","name":"Projeto Tamar Noronha","description":"Centro de educação ambiental com programação sobre tartarugas e conservação marinha.","category":"Educação ambiental","location":"Boldró","latitude":-3.8496,"longitude":-32.4198},
  {"id":"CURATED-POINT-31","mapSearchType":"POINT","name":"Trilha Capim-Açu","description":"Trilha longa e exigente por vegetação, costões e paisagens menos urbanas da ilha.","category":"Trilha","location":"Parque Nacional Marinho","latitude":-3.857,"longitude":-32.4202},
  {"id":"CURATED-POINT-32","mapSearchType":"POINT","name":"Trilha Costa Esmeralda","description":"Caminhada que conecta praias do mar de dentro, mirantes e paradas para banho.","category":"Trilha","location":"Costa oeste","latitude":-3.8486,"longitude":-32.426},
  {"id":"CURATED-POINT-33","mapSearchType":"POINT","name":"Trilha Costa Azul","description":"Roteiro costeiro de visual aberto, com trechos de banho e observação da vida marinha.","category":"Trilha","location":"Mar de fora","latitude":-3.8449,"longitude":-32.3972},
  {"id":"CURATED-RESTAURANT-34","mapSearchType":"RESTAURANT","name":"Restaurante do Vale","description":"Cozinha brasileira contemporânea em uma das regiões mais procuradas da ilha.","category":"Brasileira","location":"Vila dos Remédios","averagePrice":180,"rating":4.8,"latitude":-3.8408,"longitude":-32.4112},
  {"id":"CURATED-RESTAURANT-35","mapSearchType":"RESTAURANT","name":"O Pico","description":"Restaurante e bar central com clima descontraído, drinks e pratos autorais.","category":"Bar e restaurante","location":"Vila dos Remédios","averagePrice":150,"rating":4.6,"latitude":-3.8413,"longitude":-32.4108},
  {"id":"CURATED-RESTAURANT-36","mapSearchType":"RESTAURANT","name":"Xica da Silva","description":"Restaurante conhecido por pratos regionais, frutos do mar e ambiente acolhedor.","category":"Regional","location":"Floresta Nova","averagePrice":170,"rating":4.5,"latitude":-3.8443,"longitude":-32.414},
  {"id":"CURATED-RESTAURANT-37","mapSearchType":"RESTAURANT","name":"Varanda Noronha","description":"Cozinha brasileira com peixes, frutos do mar e atendimento voltado ao jantar.","category":"Brasileira","location":"Vila do Trinta","averagePrice":160,"rating":4.5,"latitude":-3.8446,"longitude":-32.4107},
  {"id":"CURATED-RESTAURANT-38","mapSearchType":"RESTAURANT","name":"Mergulhão","description":"Restaurante na região do Porto, famoso pelo visual e por pratos de frutos do mar.","category":"Frutos do mar","location":"Porto de Santo Antônio","averagePrice":190,"rating":4.4,"latitude":-3.833,"longitude":-32.4026},
  {"id":"CURATED-RESTAURANT-39","mapSearchType":"RESTAURANT","name":"Cacimba Bistrô","description":"Bistrô no centro histórico, próximo à Igreja dos Remédios, com pratos autorais.","category":"Bistrô","location":"Vila dos Remédios","photoUrl":"/assets/places/cacimba-bistro.jpg","averagePrice":170,"rating":4.5,"latitude":-3.8407,"longitude":-32.4114},
  {"id":"CURATED-RESTAURANT-40","mapSearchType":"RESTAURANT","name":"Benedita Cozinha Afetiva","description":"Cozinha afetiva brasileira com proposta intimista para jantar.","category":"Brasileira","location":"Vila dos Remédios","averagePrice":180,"rating":4.5,"latitude":-3.8414,"longitude":-32.4117},
  {"id":"CURATED-RESTAURANT-41","mapSearchType":"RESTAURANT","name":"Mesa da Ana","description":"Experiência gastronômica intimista com menu autoral e reservas disputadas.","category":"Menu degustação","location":"Floresta Velha","averagePrice":260,"rating":4.6,"latitude":-3.8454,"longitude":-32.4131},
  {"id":"CURATED-RESTAURANT-42","mapSearchType":"RESTAURANT","name":"Márcio Sushi","description":"Sushi e frutos do mar com foco em peixe fresco e ambiente casual.","category":"Japonesa","location":"Vila dos Remédios","averagePrice":150,"rating":4.7,"latitude":-3.8419,"longitude":-32.4113},
  {"id":"CURATED-RESTAURANT-43","mapSearchType":"RESTAURANT","name":"Acqua Noronha","description":"Restaurante com menu variado, boas opções de peixes e pratos para compartilhar.","category":"Contemporânea","location":"Vila dos Remédios","averagePrice":150,"rating":4.6,"latitude":-3.8425,"longitude":-32.4116},
  {"id":"CURATED-RESTAURANT-44","mapSearchType":"RESTAURANT","name":"Cigana do Cajueiro","description":"Cozinha regional com personalidade local e pratos de frutos do mar.","category":"Regional","location":"Vila dos Remédios","averagePrice":140,"rating":4.6,"latitude":-3.8418,"longitude":-32.4121},
  {"id":"CURATED-RESTAURANT-45","mapSearchType":"RESTAURANT","name":"Bar do Meio","description":"Bar de praia para pôr do sol, petiscos e drinks entre Conceição e Meio.","category":"Bar de praia","location":"Praia do Meio","averagePrice":120,"rating":4.4,"latitude":-3.8411,"longitude":-32.4161},
  {"id":"CURATED-RESTAURANT-46","mapSearchType":"RESTAURANT","name":"Duda Rei Bar","description":"Bar casual muito procurado para bebidas, petiscos e clima de praia.","category":"Bar","location":"Praia da Conceição","averagePrice":100,"rating":4.3,"latitude":-3.842,"longitude":-32.4173},
  {"id":"CURATED-RESTAURANT-47","mapSearchType":"RESTAURANT","name":"Empório São Miguel","description":"Opção prática no centro para lanches, refeições rápidas e apoio ao passeio.","category":"Lanches","location":"Vila dos Remédios","averagePrice":80,"rating":4.2,"latitude":-3.841,"longitude":-32.4104},
  {"id":"CURATED-RESTAURANT-48","mapSearchType":"RESTAURANT","name":"Flamboyant","description":"Restaurante tradicional para almoço e pratos brasileiros no centro da ilha.","category":"Brasileira","location":"Vila dos Remédios","averagePrice":110,"rating":4.2,"latitude":-3.8416,"longitude":-32.4109},
  {"id":"CURATED-HOTEL-49","mapSearchType":"HOTEL","name":"Pousada Maravilha","description":"Hospedagem de alto padrão próxima ao Sueste, com vista marcante e serviço completo.","category":"Luxo","location":"Sueste","averagePrice":1800,"rating":4.8,"latitude":-3.8629,"longitude":-32.4217},
  {"id":"CURATED-HOTEL-50","mapSearchType":"HOTEL","name":"NANNAI Noronha","description":"Hospedagem premium com restaurante e experiência voltada ao descanso.","category":"Luxo","location":"Sueste","averagePrice":2200,"rating":4.8,"latitude":-3.8633,"longitude":-32.4223},
  {"id":"CURATED-HOTEL-51","mapSearchType":"HOTEL","name":"Teju-Açu Eco Pousada","description":"Pousada de charme com proposta integrada à natureza e gastronomia reconhecida.","category":"Charme","location":"Floresta Velha","averagePrice":1600,"rating":4.7,"latitude":-3.8469,"longitude":-32.4173},
  {"id":"CURATED-HOTEL-52","mapSearchType":"HOTEL","name":"Dolphin Hotel","description":"Hotel com estrutura de lazer e localização prática para circular pela ilha.","category":"Hotel","location":"Floresta Nova","averagePrice":900,"rating":4.4,"latitude":-3.846,"longitude":-32.415},
  {"id":"CURATED-HOTEL-53","mapSearchType":"HOTEL","name":"Pousada do Vale","description":"Pousada central, arborizada e próxima à Vila dos Remédios.","category":"Charme","location":"Vila dos Remédios","averagePrice":1100,"rating":4.6,"latitude":-3.8406,"longitude":-32.4117},
  {"id":"CURATED-HOTEL-54","mapSearchType":"HOTEL","name":"Pousada Morena","description":"Hospedagem de charme com vista para o Morro do Pico e boa estrutura.","category":"Charme","location":"Floresta Velha","averagePrice":1300,"rating":4.6,"latitude":-3.8449,"longitude":-32.4147},
  {"id":"CURATED-HOTEL-55","mapSearchType":"HOTEL","name":"Pousada Zé Maria","description":"Pousada tradicional da ilha, conhecida também por experiências gastronômicas.","category":"Tradicional","location":"Floresta Velha","averagePrice":1400,"rating":4.5,"latitude":-3.8458,"longitude":-32.4162},
  {"id":"CURATED-HOTEL-56","mapSearchType":"HOTEL","name":"Pousada Triboju","description":"Hospedagem de charme perto do centro histórico e das praias urbanas.","category":"Charme","location":"Vila dos Remédios","averagePrice":1200,"rating":4.5,"latitude":-3.8402,"longitude":-32.4121},
  {"id":"CURATED-HOTEL-57","mapSearchType":"HOTEL","name":"Solar dos Ventos","description":"Pousada com visual privilegiado na região do Sueste.","category":"Vista mar","location":"Sueste","averagePrice":1500,"rating":4.6,"latitude":-3.864,"longitude":-32.423},
  {"id":"CURATED-HOTEL-58","mapSearchType":"HOTEL","name":"Maria Bonita Noronha","description":"Pousada confortável e bem localizada para roteiros de poucos dias.","category":"Charme","location":"Floresta Nova","averagePrice":1200,"rating":4.5,"latitude":-3.8441,"longitude":-32.4138},
  {"id":"CURATED-CONVENIENCE-59","mapSearchType":"CONVENIENCE","name":"Posto de Combustível BR Noronha","description":"Ponto de abastecimento essencial para buggy, carros e motos alugadas.","category":"Posto","location":"BR-363","averagePrice":0,"rating":4,"latitude":-3.8455,"longitude":-32.4155},
  {"id":"CURATED-CONVENIENCE-60","mapSearchType":"CONVENIENCE","name":"Noronhão Supermercado","description":"Mercado amplo para compras de água, snacks, itens de praia e conveniência.","category":"Mercado","location":"Vila do Trinta","averagePrice":0,"rating":4.1,"latitude":-3.845,"longitude":-32.4109},
  {"id":"CURATED-CONVENIENCE-61","mapSearchType":"CONVENIENCE","name":"Supermercado Breakfast","description":"Mercado de apoio para café da manhã, bebidas e produtos rápidos.","category":"Mercado","location":"Floresta Nova","averagePrice":0,"rating":4,"latitude":-3.8447,"longitude":-32.4139},
  {"id":"CURATED-CONVENIENCE-62","mapSearchType":"CONVENIENCE","name":"Mercadinho Poty","description":"Mercadinho local para compras rápidas durante o roteiro.","category":"Mercadinho","location":"Vila dos Remédios","averagePrice":0,"rating":4,"latitude":-3.8415,"longitude":-32.4103},
  {"id":"CURATED-CONVENIENCE-63","mapSearchType":"CONVENIENCE","name":"Farmácia Noronha","description":"Farmácia de apoio para itens básicos, protetor, medicamentos e emergências leves.","category":"Farmácia","location":"Vila dos Remédios","averagePrice":0,"rating":4,"latitude":-3.8422,"longitude":-32.411},
  {"id":"CURATED-CONVENIENCE-64","mapSearchType":"CONVENIENCE","name":"Farmácia Ilha Farma","description":"Serviço útil para compras de saúde e higiene durante a estadia.","category":"Farmácia","location":"Vila do Trinta","averagePrice":0,"rating":4,"latitude":-3.8443,"longitude":-32.4108},
  {"id":"CURATED-CONVENIENCE-65","mapSearchType":"CONVENIENCE","name":"Feirinha da Vila dos Remédios","description":"Pequena feira e ponto de compras locais, lembranças e apoio ao visitante.","category":"Feira","location":"Vila dos Remédios","averagePrice":0,"rating":4,"latitude":-3.841,"longitude":-32.4107},
  {"id":"CURATED-CONVENIENCE-66","mapSearchType":"CONVENIENCE","name":"Banco 24 Horas Noronha","description":"Ponto de autoatendimento útil para saque e emergência financeira.","category":"Serviço","location":"Vila dos Remédios","averagePrice":0,"rating":3.8,"latitude":-3.8412,"longitude":-32.4106},
  {"id":"CURATED-CONVENIENCE-67","mapSearchType":"CONVENIENCE","name":"Aeroporto de Fernando de Noronha","description":"Principal chegada aérea da ilha, referência para transfers e aluguel de veículos.","category":"Transporte","location":"BR-363","averagePrice":0,"rating":4.1,"latitude":-3.8549,"longitude":-32.4233},
  {"id":"CURATED-TOUR-68","mapSearchType":"TOUR","name":"Ingresso Parque Nacional Marinho","description":"Ingresso oficial do Parque Nacional Marinho de Fernando de Noronha. Brasileiros pagam R$ 192,00 e o publico geral paga R$ 384,00; a validade informada pelo parque e de 10 dias.","category":"Ingresso","location":"Centro de Visitantes ICMBio / Parnanoronha","averagePrice":192,"latitude":-3.849,"longitude":-32.419},
  {"id":"CURATED-TOUR-69","mapSearchType":"TOUR","name":"Ilha Tour 360","description":"Passeio terrestre de dia inteiro para conhecer praias, mirantes e pontos clássicos da ilha.","category":"Ilha Tour","location":"Agências locais","averagePrice":342,"latitude":-3.8415,"longitude":-32.4116},
  {"id":"CURATED-TOUR-70","mapSearchType":"TOUR","name":"Passeio de barco Mar de Dentro","description":"Navegação pelo mar de dentro com vista para ilhas secundárias, Sancho e Dois Irmãos.","category":"Barco","location":"Porto de Santo Antônio","averagePrice":323,"latitude":-3.8332,"longitude":-32.4042},
  {"id":"CURATED-TOUR-71","mapSearchType":"TOUR","name":"Canoa havaiana ao amanhecer","description":"Experiência em canoa para ver a ilha de outro ângulo e aproveitar o mar cedo.","category":"Canoa","location":"Praia do Porto","averagePrice":null,"latitude":-3.8334,"longitude":-32.4046},
  {"id":"CURATED-TOUR-72","mapSearchType":"TOUR","name":"Mergulho de batismo","description":"Mergulho acompanhado para iniciantes em pontos protegidos de Noronha.","category":"Mergulho","location":"Porto de Santo Antônio","averagePrice":null,"latitude":-3.833,"longitude":-32.4036},
  {"id":"CURATED-TOUR-73","mapSearchType":"TOUR","name":"Mergulho credenciado","description":"Saídas para mergulhadores certificados em pontos avançados do arquipélago.","category":"Mergulho","location":"Porto de Santo Antônio","averagePrice":null,"latitude":-3.833,"longitude":-32.4036},
  {"id":"CURATED-TOUR-74","mapSearchType":"TOUR","name":"Prancha submarina","description":"Passeio de barco com prancha rebocada para observar a vida marinha em movimento.","category":"Snorkel","location":"Porto de Santo Antônio","averagePrice":215,"latitude":-3.8332,"longitude":-32.4041},
  {"id":"CURATED-TOUR-75","mapSearchType":"TOUR","name":"Snorkel no naufrágio do Porto","description":"Flutuação na região do Porto com foco no naufrágio e vida marinha.","category":"Snorkel","location":"Praia do Porto","averagePrice":null,"latitude":-3.8334,"longitude":-32.4046},
  {"id":"CURATED-TOUR-76","mapSearchType":"TOUR","name":"Trilha Atalaia curta","description":"Trilha agendada até a piscina natural da Atalaia, com regras de conservação.","category":"Trilha","location":"Atalaia","averagePrice":null,"latitude":-3.8438,"longitude":-32.3958},
  {"id":"CURATED-TOUR-77","mapSearchType":"TOUR","name":"Trilha Atalaia longa","description":"Roteiro guiado com piscinas naturais e caminhada por trecho sensível do Parque.","category":"Trilha","location":"Atalaia","averagePrice":null,"latitude":-3.8438,"longitude":-32.3958},
  {"id":"CURATED-TOUR-78","mapSearchType":"TOUR","name":"Trilha Capim-Açu guiada","description":"Trilha longa para viajantes com preparo físico e interesse em paisagens menos óbvias.","category":"Trilha","location":"Parque Nacional","averagePrice":null,"latitude":-3.857,"longitude":-32.4202},
  {"id":"CURATED-TOUR-79","mapSearchType":"TOUR","name":"Trilha Costa Esmeralda","description":"Caminhada pela sequência de praias do mar de dentro, com paradas para banho.","category":"Trilha","location":"Costa oeste","averagePrice":null,"latitude":-3.8486,"longitude":-32.426},
  {"id":"CURATED-TOUR-80","mapSearchType":"TOUR","name":"Trilha Costa Azul","description":"Experiência guiada no mar de fora com visual costeiro e orientação ambiental.","category":"Trilha","location":"Mar de fora","averagePrice":null,"latitude":-3.8449,"longitude":-32.3972},
  {"id":"CURATED-TOUR-81","mapSearchType":"TOUR","name":"Lancha privativa","description":"Passeio personalizado de lancha para grupos, com paradas para banho e contemplação.","category":"Barco","location":"Porto de Santo Antônio","averagePrice":null,"latitude":-3.8332,"longitude":-32.4042},
  {"id":"CURATED-TOUR-82","mapSearchType":"TOUR","name":"Entardecer no barco","description":"Navegação curta no fim do dia com vista do pôr do sol a partir do mar.","category":"Barco","location":"Porto de Santo Antônio","averagePrice":362,"latitude":-3.8332,"longitude":-32.4042},
  {"id":"CURATED-TOUR-83","mapSearchType":"TOUR","name":"Bike aquática","description":"Atividade leve no mar para fotos e contemplação perto das praias urbanas.","category":"Aventura","location":"Praia da Conceição","averagePrice":null,"latitude":-3.8422,"longitude":-32.4173},
  {"id":"CURATED-TOUR-84","mapSearchType":"TOUR","name":"Observação de golfinhos","description":"Saída cedo para observar golfinhos e entender o comportamento da espécie.","category":"Natureza","location":"Mirante dos Golfinhos","averagePrice":null,"latitude":-3.8524,"longitude":-32.4446},
  {"id":"CURATED-TOUR-85","mapSearchType":"TOUR","name":"Tour histórico Vila dos Remédios","description":"Caminhada guiada pela igreja, fortaleza, palácio e casario histórico.","category":"Cultura","location":"Vila dos Remédios","averagePrice":null,"latitude":-3.8409,"longitude":-32.4108},
  {"id":"CURATED-TOUR-86","mapSearchType":"TOUR","name":"Experiência Projeto Tamar","description":"Visita orientada e palestra para entender conservação de tartarugas marinhas.","category":"Educação ambiental","location":"Boldró","averagePrice":null,"latitude":-3.8496,"longitude":-32.4198},
  {"id":"CURATED-TOUR-87","mapSearchType":"TOUR","name":"Transfer aeroporto e praias","description":"Serviço de deslocamento para chegada, saída e praias com acesso por estrada.","category":"Transporte","location":"Aeroporto","averagePrice":null,"latitude":-3.8549,"longitude":-32.4233},
  {"id":"CURATED-TOUR-88","mapSearchType":"TOUR","name":"Aluguel de buggy","description":"Locação para circular pela ilha com autonomia entre praias, mirantes e restaurantes.","category":"Transporte","location":"BR-363","averagePrice":null,"latitude":-3.8453,"longitude":-32.4145},
];
